// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5CFDNVrDRVCYVQk9DyVhArhlG_fxBdUA',
    appId: '1:1003186192537:web:fe420f9fa8ae89a70ab808',
    messagingSenderId: '1003186192537',
    projectId: 'stellar-vision-9cc3f',
    authDomain: 'stellar-vision-9cc3f.firebaseapp.com',
    databaseURL: 'https://stellar-vision-9cc3f-default-rtdb.firebaseio.com',
    storageBucket: 'stellar-vision-9cc3f.firebasestorage.app',
    measurementId: 'G-G7R3RRE8HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFolyfmKLokObo3iK7jRXJT6oTYuv29gk',
    appId: '1:1003186192537:android:f6435f5b788e010c0ab808',
    messagingSenderId: '1003186192537',
    projectId: 'stellar-vision-9cc3f',
    databaseURL: 'https://stellar-vision-9cc3f-default-rtdb.firebaseio.com',
    storageBucket: 'stellar-vision-9cc3f.firebasestorage.app',
  );

}